# create cutout params
# specify region and resolution
cutout:
  dx: 0.25
  dy: 0.25
  path: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/cutout/" # fname: name + _ + year + .nc
  region: # Data currently pulled from GADM for canada
    name: "BC"
    file: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/regions/gadm41_CAN_1.json"
  snapshots:
    start: # Other usages assume this is in format of 'YYYY-MM-DD'
      - '2021-01-01' # YYYY-MM-DD
    end:
      - '2021-12-31' # YYYY-MM-DD
  source: "era5"
  # file: "/mnt"

# Used to specify scope for running PyPSA_BC
# 1) Temporal
# 2) Spatial
# 3) Technical
scope:
  temporal:
    start: '2021-01-01 00:00:00' # YYYY-MM-DD HH-MM-##
    end: '2021-12-31 23:00:00' # YYYY-MM-DD HH-MM-##

# read-only files
# hydro data for the basins hardcoded for NA and Artic this would
# need to be modified to be used internationally
basin_files:
  na_file: '/mnt/c/Users/pmcw9/Delta-E/PICS/Data/hydroBASINS/hybas_na_lev12_v1c.shp'
  artic_file: '/mnt/c/Users/pmcw9/Delta-E/PICS/Data/hydroBASINS_artic/hybas_ar_lev12_v1c.shp'

# CODERS file locations (inputs)
coders:
  gen_generic: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/supply/generation_generic.csv"
  hydro_existing: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/supply/hydro_existing.csv"
  generators: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/supply/generators.csv"
  hydro_cascade: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/supply/hydro_cascade.csv"
  lines: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/network/transmission_lines.csv"
  substations: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/SESIT/CODERS/data-pull/network/substations.csv"

# network configuration
network:
  folder: "/home/pmcwhannel/repos/PyPSA_BC/results/pypsa-network"

# Custom datasets
custom:
  line_table: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/custom/electric_power_generation_table_13_3a.xlsx"

# BC Hydro derived files (inputs)
bc_hydro:
  generation_wup: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/custom/hydro_gen_wup_features.csv"
  reservoir_wup: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/custom/hydro_res_wup_features.csv"
  inflow_tables: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/custom/inflow_stats"
  
# read & write files hydro assets
# renamed: hydro_assets.csv -> hydro_generation.csv
hydro_prep:
  hydro_generation: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/hydro_generation.csv'
  hydro_reservoir: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/hydro_reservoirs.csv'
  cutout: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/cutout/BC_2021.nc"

# parameters for inflow of RoR
ror_inflows:
  height: True
  flowspeed: 1
  ror_outfile: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/bc_ror_power_series.csv'
  ror_assets: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/hydro_generation.csv'

# parameters for inflow of reservoirs
reservoir_inflows:
  height: False
  flowspeed: 1
  folder: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/reservoir_inflows'
  reservoir_assets: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/hydro_reservoirs.csv'
  hydro_assets:  '/home/pmcwhannel/repos/PyPSA_BC/results/interim/hydro_generation.csv'
  output: '/home/pmcwhannel/repos/PyPSA_BC/results/interim/reservoir_inflows.csv'

# wind
wind:
  can_turbines: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/wind/canada_turbines.xlsx"
  turbine_dict: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/wind/turbine_dict.json"
  asset_path: "/home/pmcwhannel/repos/PyPSA_BC/results/bc_wind_assets.csv"
  atlas_speed: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/wind/british_columbia_wspd_100m.tif"
  atlas_geojson: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/wind/british_columbia.geojson"
  calibration: 0
  ts_path: "/home/pmcwhannel/repos/PyPSA_BC/results/wind_ts.csv"

#
solar:
  asset_path: "/home/pmcwhannel/repos/PyPSA_BC/results/bc_pv_assets.csv"
  calibration: 0
  ts_path: "/home/pmcwhannel/repos/PyPSA_BC/results/pv_ts.csv"

# parameters for the vre enrichment
# These are shared for solar and wind 
vre:
  asset_path: "/home/pmcwhannel/repos/PyPSA_BC/results/bc_pv_assets.csv" # wind/pv
  ts_path: "/home/pmcwhannel/repos/PyPSA_BC/results/pv_ts.csv" # wind/pv
  type: "solar" # "wind" or "solar"

# thermal power plant setups and grid related settings.
tpp:
  gas_grid: False # True means the thermal generators will have unique gas bus at each of their nodes.
  UC: False # unit commitment for thermal PPs


# load related configuration (i.e. Paths to data files)
load:
  ceei: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/load/CEEI_2020.xlsx"
  municipality: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/load/municipality.csv"
  bch: "/mnt/c/Users/pmcw9/Delta-E/PICS/Data/load/bc_hydro_load/BalancingAuthorityLoad2021.xls"
  year: 2021 # temporary parameter for the BC Hydro load year selection
  res_path: "/home/pmcwhannel/repos/PyPSA_BC/results/hourly_res.csv" # output path
  csmi_path: "/home/pmcwhannel/repos/PyPSA_BC/results/hourly_csmi.csv" # output path
  # "C:\Users\pmcw9\Delta-E\PICS\Data\load\bc_hydro_load\BalancingAuthorityLoad2015.xls"

# PyPSA : path and file names for creating dictionary used to instantiate assets in PyPSA
pypsa_dict:
  components: "/home/pmcwhannel/repos/PyPSA_BC/results/pypsa-components/"
  hydro_net: "/home/pmcwhannel/repos/PyPSA_BC/results/pypsa-network/"
  hydro_res: "hydro_reservoirs.pickle"
  hydro_ror: "hydro_ror.pickle"
  wind: "wind_farms.pickle"
  solar: "pv.pickle"
  tpp: "tpp.pickle"

pypsa:
  results: "/home/pmcwhannel/repos/PyPSA_BC/results/network_results.nc"